require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'docs/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100
