default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('TODO_DATABASE') { 'todo_database' } %>

test:
  <<: *default
  database: <%= ENV.fetch('TODO_DATABASE') { 'todo_database_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('TODO_DATABASE') { 'todo_database_production' } %>
